// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  require('./jquery.payment');

  $ = jQuery;

  $.fn.formance.creditCardCVC = {
    format: function() {
      this.payment('formatCardExpiry');
      return this;
    },
    validate: function() {
      var type, val;

      val = $(this).val();
      type = null;
      return $.payment.validateCardCVC(val, type);
    },
    parse: function(expiryString) {
      return $.payment.cardExpiryVal(expiryString);
    }
  };

}).call(this);
