// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  require('./jquery.payment');

  $ = jQuery;

  $.formance.fn.formatCreditCardCVC = function() {
    this.payment('formatCardCVC');
    return this;
  };

  $.formance.validateCreditCardCVC = function(val, type) {
    return $.payment.validateCardCVC(val, type);
  };

}).call(this);
