// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  require('./jquery.payment');

  $ = jQuery;

  $.formance.fn.formatCreditCardExpiry = function() {
    this.payment('formatCardExpiry');
    return this;
  };

  $.formance.validateCreditCardExpiry = function(month, year) {
    return $.payment.validateCardExpiry(month, year);
  };

  $.formance.creditCardExpiryVal = function(expiryString) {
    return $.payment.cardExpiryVal(expiryString);
  };

}).call(this);
