// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  require('./jquery.payment');

  $ = jQuery;

  $.fn.formance.creditCardExpiry = {
    format: function() {
      this.payment('formatCardExpiry');
      return this;
    },
    validate: function() {
      var expiry, val;

      val = $(this).val();
      expiry = this.parse(val);
      return $.payment.validateCardExpiry(expiry.month, expiry.year);
    },
    parse: function(expiryString) {
      return $.payment.cardExpiryVal(expiryString);
    }
  };

}).call(this);
