// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  require('./jquery.payment');

  $ = jQuery;

  $.formance.fn.formatCreditCardNumber = function() {
    this.payment('formatCardNumber');
    return this;
  };

  $.formance.validateCreditCardNumber = function(num) {
    return $.payment.validateCardNumber(num);
  };

  $.formance.creditCardType = function(num) {
    return $.payment.cardType(num);
  };

}).call(this);
