// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  $ = jQuery;

  $.fn.formance.number = {
    format: function() {
      this.formatters('restrictNumeric');
      return this;
    },
    validate: function() {
      var val;

      val = $(this).val();
      return /^\d+$/.test(val);
    }
  };

}).call(this);
