// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  $ = jQuery;

  $.formance.fn.formatNumber = function() {
    this.formance('restrictNumeric');
    return this;
  };

  $.formance.validateNumber = function(val) {
    return /^\d+$/.test(val);
  };

}).call(this);
